#!/usr/bin/env bash
# Script that displays information about subdomains

# Function to query DNS and format output
check_subdomain() {
    local sub="$1"
    local dom="$2"
    # shellcheck disable=SC2086
    dig "${sub}.${dom}" +noall +answer | awk -v s="$sub" '{ print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

# Main logic to handle arguments
if [ "$#" -eq 2 ]; then
    # If 2 arguments are passed (domain + subdomain), check specific subdomain
    check_subdomain "$2" "$1"
else
    # If only domain is passed, check the required list in order
    check_subdomain "www" "$1"
    check_subdomain "lb-01" "$1"
    check_subdomain "web-01" "$1"
    check_subdomain "web-02" "$1"
fi
